# Generated by Django 4.0 on 2022-10-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_one', models.TextField(max_length=1000)),
                ('field_two', models.CharField(max_length=100)),
                ('field_three', models.IntegerField()),
            ],
        ),
    ]
